#!/bin/bash

# Demo script for GitHub Spec Kit usage in the sneakershop project
# This script demonstrates how to use the specification files

echo "=================================================="
echo "    GitHub Spec Kit Demo - Nike Sneaker Shop    "
echo "=================================================="
echo ""

echo "📚 Available Specifications:"
echo ""
echo "1. Main Project Specification (.specify/spec.md)"
echo "   - Project vision and goals"
echo "   - Core features and functionality"
echo "   - Technical architecture"
echo "   - API endpoints and security standards"
echo ""
echo "2. Technical Plan (.specify/plan.md)"
echo "   - System architecture and design"
echo "   - Technology stack"
echo "   - Database schema"
echo "   - Testing and deployment strategy"
echo ""
echo "3. Project Constitution (.specify/constitution.md)"
echo "   - Core values and principles"
echo "   - Code quality standards"
echo "   - Security guidelines"
echo "   - Decision-making framework"
echo ""
echo "4. Task Specifications (.specify/tasks/)"
echo "   - add-price-alert-feature.md (Complex feature example)"
echo "   - add-search-feature.md (Simple feature example)"
echo ""

echo "=================================================="
echo "📖 Quick Commands:"
echo "=================================================="
echo ""
echo "View project specification:"
echo "  npm run spec:read"
echo ""
echo "View technical plan:"
echo "  npm run spec:plan"
echo ""
echo "View project principles:"
echo "  npm run spec:constitution"
echo ""
echo "List all task specifications:"
echo "  npm run spec:tasks"
echo ""
echo "View a specific task:"
echo "  cat .specify/tasks/add-search-feature.md"
echo ""

echo "=================================================="
echo "🚀 Example Workflow:"
echo "=================================================="
echo ""
echo "1. Read the project specification to understand the vision"
echo "   \$ npm run spec:read"
echo ""
echo "2. Review the constitution to learn the principles"
echo "   \$ npm run spec:constitution"
echo ""
echo "3. Create a new feature task specification"
echo "   \$ touch .specify/tasks/my-new-feature.md"
echo ""
echo "4. Implement the feature following the specification"
echo "   (Code implementation)"
echo ""
echo "5. Reference the task in your commit"
echo "   \$ git commit -m \"feat: implement my feature per .specify/tasks/my-new-feature.md\""
echo ""

echo "=================================================="
echo "💡 Using Spec Kit with AI Assistants:"
echo "=================================================="
echo ""
echo "When working with GitHub Copilot, Claude, or other AI assistants:"
echo ""
echo "Provide context like this:"
echo ""
echo '  "Please implement the feature described in'
echo '   .specify/tasks/add-search-feature.md'
echo ""
echo '   Context:'
echo '   - Read .specify/spec.md for project standards'
echo '   - Read .specify/constitution.md for code principles'
echo '   - Read .specify/plan.md for technical architecture'
echo ""
echo '   Follow all specifications and maintain consistency.'
echo '   "'
echo ""

echo "=================================================="
echo "📝 More Information:"
echo "=================================================="
echo ""
echo "  • Spec Kit README: .specify/README.md"
echo "  • Project README: README.md"
echo "  • Contributing Guide: CONTRIBUTING.md"
echo "  • Official Spec Kit: https://github.com/github/spec-kit"
echo "  • Spec Kit Docs: https://speckit.org/"
echo ""
echo "=================================================="
echo "✨ Happy Spec-Driven Development!"
echo "=================================================="
